uploader:
  name: qiniu
  moduele: pypicgo.uploaders.qiniu.uploader.QiNiuUploader
  config:
    domain: http://demo.pypicho.com/
    bucket_name: pypicgo
    apis:
      - http://up-z1.qiniup.com
    access_key: xxx
    secret_key:  xxxx
plugins:
  - module: pypicgo.plugins.rename.ReNamePlugin
    config:


