uploader:
  name: gitee
  module: pypicgo.uploaders.gitee.uploader.GiteeUploader
  config:
    owner: Ranger313
    repo: pbed
    img_path: PyPicGo
    oauth_token:  xxx
plugins:
  - module: pypicgo.plugins.rename.ReNamePlugin
    config:
