uploader:
  name: github
  module: pypicgo.uploaders.github.uploader.GithubUploader
  config:
    owner: Ranger313
    repo: pbed
    img_path: PyPicGo
    oauth_token:  xxx
plugins:
  - module: pypicgo.plugins.rename.ReNamePlugin
    config:
